#!/usr/bin/env python3
"""
Read Moodle activity .csv files and output requested lists or interactive plots

"""
import sys
import argparse
import mootler.src.course_data as cd

def main(args):
    # read in files, option to filter by users
    if args.users_file:
        cdat = cd.read_cd_csvs(args.activity_file, args.users_file)
        cdat.filter_users()
    else:
        cdat = cd.read_cd_csvs(args.activity_file)

    # filter by substring
    if args.string:
        cdat.filter_by_string(args.string, args.colstring, incomplete=True)

    print("After filtering there are {} activities.".format(len(cdat.activity)))

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("activity_file", help="CSV file of the activities.")
    parser.add_argument("users_file", default=None, help="CSV file of users whose activity is analised. (optional)")
    parser.add_argument("-s","--string", default=None, help="Substring to be searched for.")
    parser.add_argument("-c","--colstring", default="Event context", help="Substring of the column title in which activities are searched.")

    user_input = sys.argv[1:]
    args = parser.parse_intermixed_args(user_input)
    main(args)
